server:
  port: 8080
  servlet:
    context-path:  /demo

spring:
  profiles.active: default

---
spring:
  profiles: default

  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
     
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    

---
spring:
  profiles: pcf
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/pong_matcher_spring_development
    username: springpong
    password: springpong
  
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    